services:
  - type: web
    name: loootcoin-seed
    env: python
    plan: free
    buildCommand: ""
    startCommand: python node.py --wallet seed.json --data data
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
